version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - type: volume
        source: es_data
        target: /usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - search-service

  kibana:
    image: kibana:8.6.2
    ports:
      - target: 5601
        published: 5601
    networks:
      - search-service
    depends_on:
      - elasticsearch

volumes:
  es_data:
    driver: local

networks:
  search-service:
    name: search-service
    driver: bridge